name: Build
on: [push]

jobs:
    build:
        name: Build package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn install
            - name: Run build
              run: yarn build
